### ISSUE TITLE
issue when EFI part's name have whitespace

### ISSUE THREAD

**Issue by lscgzwd** [black-dragon74/OSX-Debug#3]
if my EFI part's name have whitespace , LIKE:  "SATA EFI", the script can not work with this.

should been fixed by " cp -prf \"$efiloc/EFI/CLOVER .\" "

**Comment by lscgzwd** [comment]
> Mounted EFI at /Volumes/SATA EFI (credits RehabMan)
cp: /Volumes/SATA: No such file or directory
cp: EFI/EFI/CLOVER: No such file or directory
Removing theme dir.
/usr/bin/gen_debug: line 570: cd: ./CLOVER: No such file or directory
Removing tools dir.
Masking your System IDs
Dumped CLOVER files.
Unmounted /Volumes/SATA EFI

**Comment by black-dragon74** [comment]
Thanks for reporting mate. Fixed in version 3.3

**Comment by lscgzwd** [comment]
verify. Great!
