### ISSUE TITLE
About network ping test

### ISSUE THREAD

**Issue by y010204025** [black-dragon74/OSX-Debug#4]
Hello, black-dragon74 ,I am in China. When using the OSX-Debug script, the network is not connected. When I looked at the script, I found out that your network connection test uses google.com. I can't access google in China. I hope you can change the test network website.Such as github.com, yandex.ru, etc.

Prompt shutdown during the script run to extract log and raw dsdt may not be very intuitive, not intuitive for beginners, I suggest placing the shutdown log and the original dsdt prompts behind your version information, which is more friendly. Thank you.

Please forgive my lame English.

**Comment by black-dragon74** [comment]
[Fixed!](https://github.com/black-dragon74/OSX-Debug/commit/ebde9f33361d6764c19f095a25ac666ca5a82b8e) Thanks for reporting mate :)

P.S: Your English is not lame.

**Comment by darkrain88** [comment]
it is prefer to bing.com

github.com also is unpingable from china

**Comment by black-dragon74** [comment]
Look at: https://github.com/black-dragon74/OSX-Debug/pull/7

**Comment by MuntashirAkon** [comment]
`github.com` doesn't work here. Best is to use `raw.githubusercontent.com` for this purpose.
