### ISSUE TITLE
Lilu logs

### ISSUE THREAD

**Issue by benbaker76** [black-dragon74/OSX-Debug#6]
Can you please add the output for Lilu logs located at:
/var/log/Lilu_*

Also I noticed this line:
`ls -l /System/Library/Extensions/AppleHDA.kext/Contents/Resources/*.zml*`
Shouldn't it be *.xml*?

**Comment by nguyennb9** [comment]
It obviously, let create a PR if you have time :D

**Comment by black-dragon74** [comment]
Hey @headkaze,

Thanks for requesting this. Also regarding AppleHDA logs, in earlier versions of macOS we always had `zlib` files compressed as `zml` now I see they are using `.xml.zlib`.

Lilu logs implemented at: 5de178702f807994ed121a1ccec52f8fb9e1ea4c
AppleHDA implemented at: 57a08155968f55b5137180b0f4cde517a6a0b118

Regards
