### ISSUE TITLE
Didnt work at all

### ISSUE THREAD

**Issue by sonvirgo** [black-dragon74/OSX-Debug#8]
![Screenshot 2019-04-16 at 08 05 20](https://user-images.githubusercontent.com/10823037/56174808-85b49300-601e-11e9-91a0-cd4adbcc26c8.png)

**Comment by black-dragon74** [comment]
https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/post-1944005

**Comment by ankurbaghel** [comment]
didnt worked [
![Screen Shot 2021-01-27 at 1 43 13 PM](https://user-images.githubusercontent.com/77823633/105962335-b3f54c80-60a5-11eb-9545-29a7efdb874f.png)

**Comment by black-dragon74** [comment]
@ankurbaghel Replace `/usr/bin` To `/usr/local/bin`

**Comment by ankurbaghel** [comment]
tried sir 
![Screen Shot 2021-01-27 at 1 50 33 PM](https://user-images.githubusercontent.com/77823633/105963253-cb810500-60a6-11eb-855c-279e341ca700.png)

**Comment by black-dragon74** [comment]
Run `sudo mkdir /usr/local/bin` and then run the command to install.

**Comment by ankurbaghel** [comment]
tried 
![Screen Shot 2021-01-27 at 1 55 55 PM](https://user-images.githubusercontent.com/77823633/105963831-7abddc00-60a7-11eb-856c-e54608f80eb3.png)

**Comment by ankurbaghel** [comment]
This script is meant for Apple macOS/OSX only.

**Comment by ankurbaghel** [comment]
i want help on dsdt patching for my laptop few things are not working properly

**Comment by black-dragon74** [comment]
> This script is meant for Apple macOS/OSX only.

Try with the latest release. I pushed a fix.



> i want help on dsdt patching for my laptop few things are not working properly

Use the forums please.

**Comment by ankurbaghel** [comment]
IOREG dump failed. Retrying by increasing delays...

**Comment by ankurbaghel** [comment]
IOREG dump failed. Retrying by increasing delays...
Increased delay by x3 times. Retrying...

**Comment by ankurbaghel** [comment]
worked thankyou sooo much sir

**Comment by black-dragon74** [comment]
Alright. Have a good day!
